name: Astroberry OS sysmod

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    strategy:
      fail-fast: false
      matrix:
        distro: ["debian-trixie"]
        architecture: ["arm64", "amd64"]

    container:
      image: ghcr.io/${{ github.repository }}/${{ matrix.distro }}-${{ matrix.architecture }}

    steps:
      - name: Get the sources
        uses: actions/checkout@v6
        with:
          repository: 'astroberry-official/astroberry-os-sysmod'
          path: 'astroberry-os-sysmod'

      - name: Build Astroberry OS sysmod
        run: |
          rm -rf build/deb_astroberry-os-sysmod && mkdir -p build/deb_astroberry-os-sysmod && \
          cp -r astroberry-os-sysmod/* build/deb_astroberry-os-sysmod/ && cd build/deb_astroberry-os-sysmod && \
          fakeroot debian/rules binary
