name: Astroberry OS builder
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    strategy:
      fail-fast: false
      matrix:
        distro: ["debian-trixie"]
        platform: ["arm64"]

    steps:
      - name: Login to Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          platforms: linux/${{ matrix.platform }}
          file: docker/Dockerfile.${{ matrix.distro }}
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ matrix.distro }}-${{ matrix.platform }}
