name: Astroberry OS image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    strategy:
      fail-fast: false
      matrix:
        container: ["debian-trixie"]

    container:
      image: ghcr.io/${{ github.repository }}/${{ matrix.container }}
      volumes:
        - /dev:/dev
      options: --privileged

    steps:
      - name: Get sources
        uses: actions/checkout@v6
        with:
          repository: astroberry-official/astroberry-os
          path: astroberry-os

      - name: Install required tools
        run: |
          apt-get update && apt-get install -y wget parted gzip pigz xz-utils udev e2fsprogs && \
          wget https://raw.githubusercontent.com/Drewsif/PiShrink/master/pishrink.sh && \
          chmod +x pishrink.sh && mv pishrink.sh /usr/local/bin/

      - name: Setup variables
        run: |
          IMAGE_URL="https://downloads.raspberrypi.org/raspios_lite_arm64/images/raspios_lite_arm64-2025-12-04" && echo "IMAGE_URL=$IMAGE_URL" >> $GITHUB_ENV
          INPUT_IMAGE="2025-12-04-raspios-trixie-arm64-lite.img" && echo "INPUT_IMAGE=$INPUT_IMAGE" >> $GITHUB_ENV
          # IMPORTANT! image file naming convention: astroberry_x.x_debian-trixie-arm64.img, where x.x is version number e.g 3.0
          OUTPUT_IMAGE="astroberryos_3.1_${{ matrix.container }}-arm64.img" && echo "OUTPUT_IMAGE=$OUTPUT_IMAGE" >> $GITHUB_ENV

      - name: Download Raspberry Pi OS image
        run: |
          wget -c "$IMAGE_URL/$INPUT_IMAGE.xz"
          wget -c "$IMAGE_URL/$INPUT_IMAGE.xz.sha256"
          cat "$INPUT_IMAGE.xz.sha256"
          sha256sum -c "$INPUT_IMAGE.xz.sha256"

      - name: Extract Raspberry Pi OS image
        run: |
          xz -d -k -f "$INPUT_IMAGE.xz"
          mv "$INPUT_IMAGE" "$OUTPUT_IMAGE"
          ls -alh "$OUTPUT_IMAGE"

      - name: Grow image +7GB
        run: |
          dd if=/dev/zero bs=1M count=7168 >> "$OUTPUT_IMAGE"
          ls -alh "$OUTPUT_IMAGE"

      - name: Build Astroberry OS image
        run: |
          astroberry-os/scripts/astroberry-image-build.sh "$OUTPUT_IMAGE"
          ls -alh "$OUTPUT_IMAGE"

      - name: Shrink and compress Astroberry OS image
        run: |
          if [ -e "$OUTPUT_IMAGE.xz" ]; then rm -rf "$OUTPUT_IMAGE.xz"; fi
          pishrink.sh -asZv "$OUTPUT_IMAGE"
          ls -alh "$OUTPUT_IMAGE.xz"

      - name: Generate checksums
        run: |
          sha256sum "$OUTPUT_IMAGE.xz" > "$OUTPUT_IMAGE.xz.sha256"
          cat "$OUTPUT_IMAGE.xz.sha256"
          sha256sum -c "$OUTPUT_IMAGE.xz.sha256"
