name: Astroberry OS image (amd64)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    strategy:
      fail-fast: false
      matrix:
        distro: ["debian-trixie"]
        architecture: ["amd64"]

    container:
      image: ghcr.io/${{ github.repository }}/${{ matrix.distro }}-${{ matrix.architecture }}
      volumes:
        - /dev:/dev
      options: --privileged

    steps:
      - name: Get sources
        uses: actions/checkout@v6
        with:
          repository: astroberry-official/astroberry-os
          path: astroberry-os

      - name: Install required tools
        run: |
          apt-get update && apt-get install -y wget parted gzip pigz xz-utils udev e2fsprogs debootstrap zstd \
            xorriso grub-pc-bin grub-efi-amd64-bin shim-signed mtools libisoburn1 cpio dosfstools

      - name: Setup variables
        run: |
          OUTPUT_IMAGE="astroberryos_3.2_${{ matrix.distro }}-${{ matrix.architecture }}.iso" && echo "OUTPUT_IMAGE=$OUTPUT_IMAGE" >> $GITHUB_ENV

      - name: Build Astroberry OS image
        run: |
          astroberry-os/scripts/astroberry-image-build-amd64.sh "$OUTPUT_IMAGE"
          ls -alh "$OUTPUT_IMAGE"

      - name: Generate checksums
        run: |
          sha256sum "$OUTPUT_IMAGE" > "$OUTPUT_IMAGE.sha256"
          cat "$OUTPUT_IMAGE.sha256"
          sha256sum -c "$OUTPUT_IMAGE.sha256"
