name: Build INDI 3rd Party Libraries

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    strategy:
      fail-fast: false
      matrix:
        container: ["debian-trixie"]

    container:
      image: ghcr.io/${{ github.repository }}/${{ matrix.container }}-${{ vars.ARCH }}

    steps:
      - name: Get INDI 3rd Party Sources
        uses: actions/checkout@v6
        with:
          repository: 'indilib/indi-3rdparty'
          ref: refs/tags/v2.2.0
          path: 'indi-3rdparty'

      - name: Fix INDI 3rd Party Sources
        run: |
          for i in $(ls indi-3rdparty/debian/*/rules);do chmod 755 $i; done
          sed -i "s/^lib/usr\/lib/g" indi-3rdparty/debian/lib*/*.install

      - name: Install INDI Core
        run: |
          dpkg -i build/indi-bin_*_arm64.deb build/libindi1_*_arm64.deb build/libindi-data_*_all.deb build/libindi-dev_*_arm64.deb

      - name: Build INDI 3rd Party Libraries
        run: |
          LIBS=$(basename -a indi-3rdparty/lib*) && \
          indi-3rdparty/scripts/indi-3rdparty-deb.sh $LIBS
