name: Build INDI 3rd Party Drivers

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    strategy:
      fail-fast: false
      matrix:
        container: ["debian-trixie"]

    container:
      image: ghcr.io/${{ github.repository }}/${{ matrix.container }}-${{ vars.ARCH }}

    steps:
      - name: Get INDI 3rd Party Sources
        uses: actions/checkout@v6
        with:
          repository: 'indilib/indi-3rdparty'
          ref: refs/tags/v2.2.0
          path: 'indi-3rdparty'

      - name: Fix INDI 3rd Party Sources
        run: |
          for i in $(ls indi-3rdparty/debian/*/rules);do chmod 755 $i;done
          sed -i "s/^lib/usr\/lib/g" indi-3rdparty/debian/indi-*/*.install
          sed -i "s/\/lib\/udev\/rules.d/\/usr\/lib\/udev\/rules.d/g" indi-3rdparty/indi-openogma/CMakeLists.txt

      - name: Install INDI Core
        run: |
          dpkg -i build/indi-bin_*_${{ vars.ARCH }}.deb build/libindi1_*_${{ vars.ARCH }}.deb build/libindi-data_*_all.deb build/libindi-dev_*_${{ vars.ARCH }}.deb

      - name: Install INDI 3rd Party Libraries
        run: |
          dpkg -i --force-overwrite $(ls build/lib* | grep -v dbgsym | grep -v libindi | grep -v dev) && dpkg -i --force-overwrite $(ls build/lib* | grep -v dbgsym | grep -v libindi | grep dev)

      - name: Build INDI 3rd Party Drivers
        run: |
          DRIVERS=$(basename -a indi-3rdparty/indi-* | grep -v indi-libcamera | grep -v indi-bno-imu | grep -v indi-celestron-origin | grep -v indi-icm-imu) && \
          indi-3rdparty/scripts/indi-3rdparty-deb.sh $DRIVERS && \
          mkdir indi-3rdparty/indi-full && \
          indi-3rdparty/scripts/indi-3rdparty-deb.sh indi-full
