name: Build KStars

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    strategy:
      fail-fast: false
      matrix:
        distro: ["debian-trixie"]
        architecture: ["arm64", "amd64"]

    container:
      image: ghcr.io/${{ github.repository }}/${{ matrix.distro }}-${{ matrix.architecture }}

    steps:
      - name: Get KStars Sources
        run: |
          if [ -d kstars ]; then rm -rf kstars; fi
          git clone --depth 1 --branch stable-3.8.2 https://invent.kde.org/education/kstars.git

      - name: Install KStars Dependencies
        run: |
          dpkg -i build/libstellarsolver_*.deb build/libstellarsolver-dev_*.deb \
          build/libindi1_*.deb build/libindi-dev_*.deb build/libindi-data_*.deb build/indi-bin_*.deb

      - name: Build Kstars Packages
        run: |
          rm -rf build/deb_kstars && mkdir -p build/deb_kstars && \
          cp -r kstars/* build/deb_kstars/ && \
          cp -r kstars/packaging/linux/debian build/deb_kstars/ && \
          cd build/deb_kstars && \
          echo "export DEB_BUILD_OPTIONS := parallel=\$(shell nproc)" >> debian/rules && \
          fakeroot debian/rules binary
