name: Build INDI Core

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    strategy:
      fail-fast: false
      matrix:
        container: ["debian-trixie"]

    container:
      image: ghcr.io/${{ github.repository }}/${{ matrix.container }}-${{ vars.ARCH }}

    steps:
      - name: Get INDI Sources
        uses: actions/checkout@v6
        with:
          repository: 'indilib/indi'
          ref: refs/tags/v2.2.0
          path: 'indi'

      - name: Build INDI Core Packages
        run: |
          indi/scripts/indi-core-deb.sh
