name: Build Astroberry Manager

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    strategy:
      fail-fast: false
      matrix:
        container: ["debian-trixie"]

    container:
      image: ghcr.io/${{ github.repository }}/${{ matrix.container }}-${{ vars.ARCH }}

    steps:

      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y python3 python-is-python3 python3-pip python3-venv \
          gobject-introspection swig libcairo2-dev libgirepository-2.0-dev libdbus-1-dev libcfitsio-dev libnova-dev
          dpkg -i build/indi-bin_*_arm64.deb build/libindi1_*_arm64.deb build/libindi-data_*_all.deb build/libindi-dev_*_arm64.deb

      - name: Get the sources of Astroberry Manager
        uses: actions/checkout@v6
        with:
          repository: 'astroberry-official/astroberry-manager'
          path: 'astroberry-manager'

      - name: Build Astroberry Manager
        run: |
          rm -rf build/whl_astroberry-manager && mkdir -p build/whl_astroberry-manager && \
          cp -r astroberry-manager/* build/whl_astroberry-manager/ && \
          python -m venv build/whl_astroberry-manager/.venv && . build/whl_astroberry-manager/.venv/bin/activate && \
          python -m pip install build && \
          cd build/whl_astroberry-manager && python -m build && cd ../../ && deactivate
