name: Build Astroberry Manager

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    strategy:
      fail-fast: false
      matrix:
        distro: ["debian-trixie"]
        architecture: ["arm64", "amd64"]

    container:
      image: ghcr.io/${{ github.repository }}/${{ matrix.distro }}-${{ matrix.architecture }}

    steps:

      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y python3 dh-python python3-setuptools pybuild-plugin-pyproject python3-pytest

      - name: Get the sources of Astroberry Manager
        uses: actions/checkout@v6
        with:
          repository: 'astroberry-official/astroberry-manager'
          path: 'astroberry-manager'

      - name: Build Astroberry Manager
        run: |
          rm -rf build/deb_astroberry-manager && mkdir -p build/deb_astroberry-manager && \
          cp -r astroberry-manager/* build/deb_astroberry-manager/ && \
          cd build/deb_astroberry-manager && \
          fakeroot debian/rules binary
